# Generated by Django 6.0.4 on 2026-05-15 02:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HecatesHearthapi', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StoryPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='story_photos')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='story_photos', to='HecatesHearthapi.location')),
                ('story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='HecatesHearthapi.story')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='story_photos', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
