# Generated by Django 6.0.4 on 2026-05-16 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HecatesHearthapi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='storyphoto',
            name='haunting_types',
            field=models.ManyToManyField(related_name='story_photos', to='HecatesHearthapi.hauntingtype'),
        ),
    ]
